name: Test and Build

on:
  pull_request:
    branches:
      - development
env:
  FLUTTER_VERSION: stable

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Install libsodium
        run: brew install libsodium
      - name: Dependencies check
        run: flutter pub outdated --no-dev-dependencies
      - name: Test
        run: flutter test
            
  build-android:
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Install libsodium
        run: brew install libsodium
      - name: Build for Android
        run: cd example && flutter build apk

  build-ios:
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Install libsodium
        run: brew install libsodium
      - name: Build iOS
        run: cd example && flutter create . && flutter build ios --no-codesign
